/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "PLCameraControllerDelegate-Protocol.h"
#import "PLVideoViewDelegate-Protocol.h"

@class MLPhotoDCFFileGroup, NSData, NSDictionary, NSString, PLCameraController, PLCameraElapsedTimeView, PLCropOverlay, PLImageTile, PLVideoView, UIImage, UIImageView, UIToolbar;

@interface PLCameraView : UIView <PLCameraControllerDelegate, PLVideoViewDelegate>
{
    UIToolbar *_cameraButtonBar;
    int _availablePictureCount;
    int _captureOrientation;
    int _photoSavingOptions;
    BOOL _manipulatingCrop;
    MLPhotoDCFFileGroup *_videoFileGroup;
    PLCameraController *_cameraController;
    PLCameraElapsedTimeView *_timeView;
    UIView *_previewView;
    UIView *_animatedCaptureView;
    UIView *_irisView;
    UIView *_staticIrisView;
    UIImageView *_shadowView;
    UIImage *_previewWellImage;
    UIImage *_temporaryThumbnailImage;
    int _pictureCapacity;
    BOOL _irisIsClosed;
    PLCropOverlay *_cropOverlay;
    PLImageTile *_imageTile;
    PLVideoView *_videoView;
    NSDictionary *_imagePickerOptions;
    id _delegate;
    int _enabledGestures;
    unsigned int _showsCropOverlay:1;
    unsigned int _allowsEditing:1;
    unsigned int _changesStatusBar:1;
    unsigned int _cropOverlayUsesTelephonyUI:1;
    unsigned int _showsCropRegion:1;
    unsigned int _allowsMultipleModes:1;
    unsigned int _capturePhotoWhenFocusFinished:1;
    unsigned int _dontAnimateVideoPreviewDown:1;
    NSString *_cropTitle;
    NSString *_cropButtonTitle;
    NSData *_lastCapturedImageData;
    unsigned int _imagePickerWantsImageData:1;
}

- (void)_playShutterSound;
- (void)_updateStatusBar;
- (void)setManipulatingCrop:(BOOL)fp8;
- (void)cameraControllerReadyStateChanged:(id)fp8;
- (void)_checkDiskSpaceAfterCapture;
- (void)_previewVideoAtPath:(id)fp8;
- (void)cameraController:(id)fp8 addedVideoAtPath:(id)fp12 withPreviewSurface:(void *)fp16 metadata:(id)fp20 wasInterrupted:(BOOL)fp24;
- (void)cameraController:(id)fp8 tookPicture:(id)fp12 withPreview:(id)fp16 jpegData:(struct __CFData *)fp20 imageProperties:(id)fp24;
- (void)_preparePreviewWellImage:(struct CGImage *)fp8 isVideo:(BOOL)fp12;
- (void)setupAnimateCameraPreviewDown:(id)fp8;
- (void)setupAnimateVideoPreviewDown:(void *)fp8;
- (void)animateCameraPreviewDown;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)_setShadowViewVisible:(BOOL)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (void)setEnabledGestures:(int)fp8;
- (void)setPhotoSavingOptions:(int)fp8;
- (int)photoSavingOptions;
- (void)_updateImageEditability;
- (void)setImagePickerOptions:(id)fp8;
- (void)setAllowsImageEditing:(BOOL)fp8;
- (void)setChangesStatusBar:(BOOL)fp8;
- (void)setShowsCropOverlay:(BOOL)fp8;
- (void)setCropOverlayUsesTelephonyUI:(BOOL)fp8;
- (void)setShowsCropRegion:(BOOL)fp8;
- (void)setCropTitle:(id)fp8 buttonTitle:(id)fp12;
- (void)setImagePickerWantsImageData:(BOOL)fp8;
- (void)setCameraButtonBar:(id)fp8;
- (id)buttonBar;
- (id)_bottomBar;
- (id)_modeSwitch;
- (id)_shutterButton;
- (void)setCameraMode:(int)fp8;
- (void)setAllowsMultipleCameraModes:(BOOL)fp8;
- (id)imageTile;
- (void)_inCallStatusChanged:(id)fp8;
- (void)_applicationResumed;
- (void)takePictureOpenIrisAnimationFinished;
- (void)takePictureCloseIrisAnimationFinished;
- (void)_shutterButtonClicked;
- (void)cameraControllerFocusFinished:(id)fp8;
- (void)timeLapseTimerFired;
- (id)_newVideoFileGroup;
- (void)_deleteVideoFileGroup;
- (void)cameraShutterClicked:(id)fp8;
- (void)_performVideoCapture;
- (void)_videoSwitchValueDidChange:(id)fp8;
- (void)cameraController:(id)fp8 modeDidChange:(int)fp12;
- (void)cameraControllerVideoCaptureDidStart:(id)fp8;
- (void)cameraControllerVideoCaptureDidStop:(id)fp8;
- (void)_simpleRemoteActionDidOccur:(id)fp8;
- (void)_updateModeSwitchVisibility;
- (void)viewWillBeDisplayed;
- (void)startPreview;
- (void)viewDidAppear;
- (void)viewWillBeRemoved;
- (void)_removeVideoCaptureFileAtPath:(id)fp8;
- (void)cropOverlayWasCancelled:(id)fp8;
- (void)cropOverlayWasOKed:(id)fp8;
- (void)cropOverlayPlay:(id)fp8;
- (void)cropOverlayPause:(id)fp8;
- (void)cropOverlay:(id)fp8 didFinishSaving:(id)fp12;
- (BOOL)imageViewIsDisplayingLandscape:(id)fp8;
- (void)willStartGesture:(int)fp8 inView:(id)fp12 forEvent:(struct __GSEvent *)fp16;
- (void)tearDownIris;
- (void)primeStaticClosedIris;
- (void)showStaticClosedIris;
- (void)hideStaticClosedIris;
- (BOOL)irisIsClosed;
- (void)closeIris:(BOOL)fp8 didFinishSelector:(SEL)fp12;
- (void)openIrisWithDidFinishSelector:(SEL)fp8;
- (void)openIrisAnimationFinished;
- (void)closeIrisAnimationFinished;
- (void)animateIrisForSuspension;
- (BOOL)videoViewShouldDisplayScrubber:(id)fp8;
- (BOOL)videoViewShouldDisplayOverlay:(id)fp8;
- (float)videoViewScrubberYOrigin:(id)fp8;
- (BOOL)videoViewCanBeginPlayback:(id)fp8;
- (void)videoViewIsReadyToBeginPlayback:(id)fp8;
- (void)videoViewDidBeginPlayback:(id)fp8;
- (void)videoViewDidPausePlayback:(id)fp8;
- (void)videoViewDidEndPlayback:(id)fp8 didFinish:(BOOL)fp12;
- (BOOL)isCameraReady;

@end

